import React from 'react'
import ItemListContainer from './ItemListContainer'

// POR AHORA PARECE QUE NO TIENE UTILIDAD PERO MAS ADELANTE PLANEO AGREGAR ALGUNA PUBLICIDAD
// Y ALGUN POSIBLE COMPONENTE MAS
// ACLARO PORQUE EN EL RUTEO PARECE QUE SE PUEDE PONER DIRECTAMENTE QUE RENDERICE ITEMLISTCONTAINER

const Home = () => {
  return <ItemListContainer />
}

export default Home
